export type TeamGroup = 'Leadership & Directors' | 'Sales Leadership';

export type TeamMember = {
  name: string;
  role: string;
  crNumber?: string;
  landline?: string;
  mobile?: string;
  email?: string;
  image: string;
  group: TeamGroup;
};

export const TEAM_MEMBERS: TeamMember[] = [
  {
    name: 'Alexander T. Lee',
    role: 'Director',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'info@pgaclubshares.com',
    image: '/images/team/alexander-t-lee-enhanced-v2.webp',
    group: 'Leadership & Directors',
  },
  {
    name: 'Chris Rey Generican',
    role: 'CEO / Director',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'info@pgaclubshares.com',
    image: '/images/team/chris-rey-generican-enhanced-v2.webp',
    group: 'Leadership & Directors',
  },
  {
    name: 'Nicolete U. David',
    role: 'Director / President / Marketing Head',
    crNumber: '02-2022-14470',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'nud@pgaclubshares.com',
    image: '/images/team/nicolete-u-david-enhanced-v2.webp',
    group: 'Leadership & Directors',
  },
  {
    name: 'Normita Q. Ramiro',
    role: 'Director / Associated Person',
    crNumber: '02-2018-00289',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'info@pgaclubshares.com',
    image: '/images/team/normita-q-ramiro-enhanced-v2.webp',
    group: 'Leadership & Directors',
  },
  {
    name: 'Elsie L. Tuason',
    role: 'Director',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'info@pgaclubshares.com',
    image: '/images/team/elsie-l-tuason.webp',
    group: 'Leadership & Directors',
  },
  {
    name: 'Roselle M. Mendoza',
    role: 'Director',
    crNumber: '02-2018-13169',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'roselle@pgaclubshares.com',
    image: '/images/team/roselle-m-mendoza.webp',
    group: 'Leadership & Directors',
  },
  {
    name: 'Ivy C. Kaushik',
    role: 'Director',
    crNumber: '02-2022-14464',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'ivy.kaushik@pgaclubshares.com',
    image: '/images/team/ivy-c-kaushik.webp',
    group: 'Leadership & Directors',
  },
  {
    name: 'Dixie Zolina-Masmela',
    role: 'General Manager -Sales',
    crNumber: '02-2018-13170',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'dixie.zolina@pgaclubshares.com',
    image: '/images/team/dixie-zolina-masmela.webp',
    group: 'Sales Leadership',
  },
  {
    name: 'Haidee E. Reyes',
    role: 'General Manager -Sales',
    crNumber: '02-2022-14462',
    landline: '+02 8646 9506',
    email: 'haidee@pgaclubshares.com',
    image: '/images/team/haidee-e-reyes.webp',
    group: 'Sales Leadership',
  },
  {
    name: 'Marc Nilo D. Samonte',
    role: 'Sales Team Head',
    crNumber: '02-2022-14468',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'marc.samonte@pgaclubshares.com',
    image: '/images/team/marc-nilo-d-samonte.webp',
    group: 'Sales Leadership',
  },
  {
    name: 'Apple T. Jaldon',
    role: 'Sales Team Head',
    crNumber: '02-2022-14464',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'apple@pgaclubshares.com',
    image: '/images/team/apple-t-jaldon.webp',
    group: 'Sales Leadership',
  },
  {
    name: 'Rodezza B. Labrador',
    role: 'Sales Team Head',
    crNumber: '02-2022-14469',
    landline: '+02 8646 9506',
    email: 'dezza.labrador@pgaclubshares.com',
    image: '/images/team/rodezza-b-labrador-enhanced-v2.webp',
    group: 'Sales Leadership',
  },
  {
    name: 'Ro-an Castillo',
    role: 'Sales Team Head',
    crNumber: '02-2022-14461',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'roan.castillo@pgaclubshares.com',
    image: '/images/team/ro-an-castillo-enhanced-v2.webp',
    group: 'Sales Leadership',
  },
  {
    name: 'Pauline Lachica',
    role: 'Sales Team Head',
    crNumber: '02-2022-14465',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'pauline.lachica@pgaclubshares.com',
    image: '/images/team/pauline-lachica-enhanced-v2.webp',
    group: 'Sales Leadership',
  },
  {
    name: 'Kristine Pabrualinan',
    role: 'Senior Sales Manager',
    crNumber: '02-2022-14721',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'tin@pgaclubshares.com',
    image: '/images/team/kristine-pabrualinan-enhanced-v2.webp',
    group: 'Sales Leadership',
  },
  {
    name: 'Anelyn O. Pantua',
    role: 'Senior Sales Manager',
    crNumber: '02-2022-14720',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'ayen@pgaclubshares.com',
    image: '/images/team/anelyn-o-pantua-enhanced-v2.webp',
    group: 'Sales Leadership',
  },
  {
    name: 'Joan Santos',
    role: 'Sales Manager',
    crNumber: '02-2022-14719',
    landline: '+02 8646 9506',
    mobile: '+63 917 955 3622',
    email: 'joan.santos@pgaclubshares.com',
    image: '/images/team/joan-santos-enhanced-v2.webp',
    group: 'Sales Leadership',
  },
];
